import './style.css'

export { default as BrandMark } from './components/ui/BrandMark.vue'
export { default as Button } from './components/ui/Button.vue'
export { default as CountUp } from './components/ui/CountUp.vue'
export { default as IconButton } from './components/ui/IconButton.vue'
export { default as Reveal } from './components/ui/Reveal.vue'
export { default as SectionHeading } from './components/ui/SectionHeading.vue'

/* App-level primitives — Vue ports of the React mirror (root components/ui/) */
export { default as AlphabetIndex } from './components/ui/AlphabetIndex.vue'
export { default as Checkbox } from './components/ui/Checkbox.vue'
export { default as CheckboxGroup } from './components/ui/CheckboxGroup.vue'
export type { CheckOption } from './components/ui/CheckboxGroup.vue'
export { default as Collapse } from './components/ui/Collapse.vue'
export { default as DataTable } from './components/ui/DataTable.vue'
export type { DataColumn, DataRow } from './components/ui/DataTable.vue'
export { default as DateRangeEditor } from './components/ui/DateRangeEditor.vue'
export { default as Dialog } from './components/ui/Dialog.vue'
export { default as DropdownMenu } from './components/ui/DropdownMenu.vue'
export type { MenuItem } from './components/ui/DropdownMenu.vue'
export { default as EmptyState } from './components/ui/EmptyState.vue'
export { default as Fab } from './components/ui/Fab.vue'
export { default as Field } from './components/ui/Field.vue'
export { default as FilterChips } from './components/ui/FilterChips.vue'
export type { ChipOption } from './components/ui/FilterChips.vue'
export { default as Input } from './components/ui/Input.vue'
export { default as Listbox } from './components/ui/Listbox.vue'
export type { ListboxOption } from './components/ui/Listbox.vue'
export { default as Pagination } from './components/ui/Pagination.vue'
export { default as Panel } from './components/ui/Panel.vue'
export { default as Popover } from './components/ui/Popover.vue'
export { default as ProductCard } from './components/ui/ProductCard.vue'
export { default as Progress } from './components/ui/Progress.vue'
export { default as Radio } from './components/ui/Radio.vue'
export { default as RadioGroup } from './components/ui/RadioGroup.vue'
export type { RadioOption } from './components/ui/RadioGroup.vue'
export { default as Select } from './components/ui/Select.vue'
export { default as SparkBars } from './components/ui/SparkBars.vue'
export { default as Sparkline } from './components/ui/Sparkline.vue'
export { default as Stat } from './components/ui/Stat.vue'
export { default as StatusDot } from './components/ui/StatusDot.vue'
export { default as Tabs } from './components/ui/Tabs.vue'
export type { TabItem } from './components/ui/Tabs.vue'
export { default as Tag } from './components/ui/Tag.vue'
export { default as TextArea } from './components/ui/TextArea.vue'
export { default as ThumbnailStrip } from './components/ui/ThumbnailStrip.vue'
export type { ThumbItem } from './components/ui/ThumbnailStrip.vue'

export { useContactDialog } from './composables/useContactDialog'
export { useTheme } from './composables/useTheme'
export type { Theme } from './composables/useTheme'
